language: node_js
node_js:
- '11'
- '10'
- '8'
cache:
  yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_ac0d26349c08_key -iv $encrypted_ac0d26349c08_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
